
use customer_behavior;

select * from customer_data;


--Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Total_Revenue
from customer_data
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount >=
(select AVG(purchase_amount) 
from customer_data)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(AVG(review_rating),2) as top_5_Products
from customer_data
group by item_purchased
order by top_5_Products desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select shipping_type, AVG(purchase_amount)  avg_amt_shipping
from customer_data
where shipping_type in ( 'Standard','Express')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, count(customer_id) as total_customers
,AVG(purchase_amount) as avg_spend,
sum(purchase_amount) as Total_Revenue
from customer_data
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    COUNT(CASE 
        WHEN discount_applied = 'Yes' THEN 1 
    END) * 100.0/ COUNT(*) AS Discount_Percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 1 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from customer_data)

select customer_segment, COUNT(previous_purchases) as Total_NO_Previous_Pur
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category? 
select *
from
(select category,item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by COUNT(customer_id) desc) as rn
from customer_data
group by category,item_purchased)t
where rn <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
COUNT(customer_id) as Repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

 select age_group, sum(purchase_amount) as total_revenue
 from customer_data
 group by age_group


